version: "3"

services:
  forwardsms:
    image:  securitypaperorg/forwardsms:latest
    volumes:
      - ./data:/data

  gammu-smsd:
    image: securitypaperorg/gammu-smsd:latest
    volumes:
      - ./data:/data
      - /dev/ttyUSB3:/dev/ttyUSB3
    privileged: true